### PR TITLE
NML2/LEMS export

### PR DESCRIPTION
**Pull request by dokato**
Currently without documentation because I didn't know how to integrate it with the rest.

I also changed the name of exporter from `brian2lems` to `nmlexport`.

### CODE REVIEW

**Comment by dokato** [comment]
It fails tests because there is no requirement for `pylems` module in `setup.py`. I wanted to add it, but - as I have made a lot of changes during GSOC there- I'm not sure whether the most recent version is available on PIP. Is there any way to install it from GIT automatically?

**Comment by mstimberg** [comment]
> It fails tests because there is no requirement for pylems module in setup.py. I wanted to add it, but - as I have made a lot of changes during GSOC there- I'm not sure whether the most recent version is available on PIP. Is there any way to install it from GIT automatically?

This is a bit tricky, since as you say I think there's no released version with your changes yet. Also, the tests are based on a conda package, so we'd need a conda package for `pylems` as well. I'll think about a solution.

About the documentation: the following two steps should be all that is needed:
1. Add your `exporter_*.rst` files to the `docs_sphinx/user` directory
2. Add the lines `exporter_user` and `exporter_developer` to the table of contents in `docs_sphinx/user/index.rst`

This should take care of everything, you can run `make html` in the `docs_sphinx` directory to create the documentation locally and check whether it looks alright. A somewhat nicer alternative to what I explained above would probably to create a new directory in `docs_sphinx/user`, say `neuroml2` and add the two files there. Then in that newly created directory you'd add a new `index.rst` file with a table of contents similar to the `index.rst` in `docs_sphinx/user`, referring to `exporter_user` and `exporter_developer`. Finally you'd have to mention that index file as `neuroml2/index` in `docs_sphinx/user/index.rst`. Hope that's somewhat clear :)

**Comment by dokato** [comment]
Ok, I updated documentation with new files and modified `user/index`, but unfortunately I didn't have a chance to test it as I got some strange error when running make: `Could not import extension sphinxcontrib.issuetracker` even after updating my Sphinx to the most recent version. In my other projects `make html` works fine.

**Comment by mstimberg** [comment]
> Ok, I updated documentation with new files and modified user/index, but unfortunately I didn't have a chance to test it as I got some strange error when running make: Could not import extension sphinxcontrib.issuetracker even after updating my Sphinx to the most recent version. In my other projects make html works fine.

Thanks, I'll have a look at it soon. We use a non-standard extension that allows to easily link to bugs in github's bug-tracker. You have to manually install the `sphinxcontrib-issuetracker` extension (e.g. with `pip`) to make it work. It is listed as a requirement for `brian2tools`, but only as an optional requirement, you'll have to install with the `[docs]` option to have the dependency taken into account.

**Comment by dokato** [comment]
Thanks for your hint how to use sphinx in `brian2tools`. Now as it works fine, after building the docs I realized that exporter's developer guide should be rather in `developer` folder so I just moved that file there in the most recent commit.

**Comment by mstimberg** [comment]
Sorry, I have been quite busy lately with other stuff and did not really have time yet to look into this.

I still don't have a clear plan what to do about the `pylems` dependency. @pgleeson: would you say that there is a plan to release a new version of `pylems`anytime soon? It does not change very much for us: since we recommend installing `brian2tools` via its conda package, we'll have to provide a conda package for `pylems`, anyway. If the `pylems`'s next release is quite far in the future, we'd do a `0.48+git20160909` package of it ourselves, but of course an official version number would lead to less potential confusion.

**Comment by mstimberg** [comment]
Um, we still have not merged this... @dokato : could you allow me to add changes to your branch (as explained here: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)? I'd then fix up the testing, etc.

@pgleeson: Do you have plans to do a pylems release any time soon? Otherwise we might just tell users to install it from github for now.

**Comment by dokato** [comment]
@mstimberg, of course, just updated.

**Comment by pgleeson** [comment]
@mstimberg The changes which were part of PRs had all been incorporated in master & the latest version v0.4.9 is on PYPI (I just now updated it with some minor changes).

**Comment by mstimberg** [comment]
Great, many thanks @pgleeson and @dokato, I'll try to polish and merge the PR soon.

**Comment by mstimberg** [comment]
Ok, I'll finally merge this -- it's about time :) I'll do some more polishing in the master branch directly (documentation, release notes, ...) and will do a 0.2 release of `brian2tools` soon.

**Pull request merged**
